version: '3'

services:
  frontend:
    build: .
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: build/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8080:80"

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./backend/bdd/db_data:/var/lib/mysql

